sudo: false

language: cpp

cache: ccache

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      dist: trusty
  allow_failures:
    - os: osx
      osx_image: xcode7.1

compiler:
  - gcc
  - clang

before_script:
- |
  export TMPDIR=`mktemp -d 2>/dev/null || mktemp -d -t 'travis_tmp_dir'`
  mkdir -pv $TMPDIR/cmake

  if [ $TRAVIS_OS_NAME == 'linux' ]; then
    CMAKE_URL="https://cmake.org/files/v3.6/cmake-3.6.0-Linux-x86_64.tar.gz"
    travis_retry wget --no-check-certificate -O - $CMAKE_URL | tar --strip-components=1 -xz -C $TMPDIR/cmake
    export CMAKE=$TMPDIR/cmake/bin/cmake
  elif [ $TRAVIS_OS_NAME == 'osx' ] ; then
    CMAKE_URL="https://cmake.org/files/v3.6/cmake-3.6.0-Darwin-x86_64.tar.gz"
    travis_retry curl -k $CMAKE_URL | tar --strip-components=1 -xz -C $TMPDIR/cmake
    export CMAKE=$TMPDIR/cmake/CMake.app/Contents/bin/cmake
  fi

- $CMAKE --version
- $CC --version
- $CXX --version

script:
- |
  if [ -z $TRAVIS_TAG ]; then
    tools/packaging/cpt.py --current-dev=tar --with-cling-url=https://github.com/vgvassilev/cling
  else
    tools/packaging/cpt.py --last-stable=tar --with-cling-url=https://github.com/vgvassilev/cling
  fi
- ccache -s

notifications:
  recipients:
  - ani07nov@gmail.com
  - vvasilev@cern.ch
  email:
    on_success: change
    on_failure: always
  template:
  - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"

before_deploy:
- export RELEASE_TARBALL=$(ls $HOME/ci/build/cling*.tar.bz2)
- echo "Deploying $RELEASE_TARBALL to GitHub releases"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: eIwVHJNxkAIi6IUYyx7qI1szsgWt3c42ugcJ1vZ6iH//+qJgks77I8dMlbRf0RUrhxpJhJPH5a6vqI/mo1Vq2vmoC8+D1DIQCbj+/WHhY71LQCPC+Wgj2JES5y1Wh91nMt4ybzb1dA8BIfeJOdCUn7ezJTGKk18N+h2jE+a/7IE=
  file: '${RELEASE_TARBALL}'
  on:
    tags: true
    repo: vgvassilev/cling
