sudo: false

language: cpp

cache: ccache

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
  allow_failures:
    - os: osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - binutils-gold
      - python
      - gcc-6
      - g++-6

before_script:
- git config --global user.email "ani07nov@gmail.com"
- git config --global user.name "Anirudha Bose"

- |
  export TMPDIR=/tmp
  mkdir -pv $TMPDIR/cmake

  if [ $TRAVIS_OS_NAME == 'linux' ]; then
    export CMAKE=$TMPDIR/cmake/bin/cmake
    CMAKE_URL="https://cmake.org/files/v3.6/cmake-3.6.0-Linux-x86_64.tar.gz"
    travis_retry wget --no-check-certificate -O - $CMAKE_URL | tar --strip-components=1 -xz -C $TMPDIR/cmake

    export CC=/usr/bin/gcc-6
    export CXX=/usr/bin/g++-6
  fi

- $CMAKE --version
- $CC --version
- $CXX --version

script:
- |
  if [ -z $TRAVIS_TAG ]; then
    tools/packaging/cpt.py --current-dev=tar --with-cling-url=https://github.com/vgvassilev/cling
  else
    tools/packaging/cpt.py --last-stable=tar --with-cling-url=https://github.com/vgvassilev/cling
  fi

notifications:
  recipients:
  - ani07nov@gmail.com
  - vvasilev@cern.ch
  email:
    on_success: change
    on_failure: always
  template:
  - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"

before_deploy:
- export RELEASE_TARBALL=$(ls $HOME/ci/build/cling*.tar.bz2)
- echo "Deploying $RELEASE_TARBALL to GitHub releases"

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: eIwVHJNxkAIi6IUYyx7qI1szsgWt3c42ugcJ1vZ6iH//+qJgks77I8dMlbRf0RUrhxpJhJPH5a6vqI/mo1Vq2vmoC8+D1DIQCbj+/WHhY71LQCPC+Wgj2JES5y1Wh91nMt4ybzb1dA8BIfeJOdCUn7ezJTGKk18N+h2jE+a/7IE=
  file: '${RELEASE_TARBALL}'
  on:
    tags: true
    repo: vgvassilev/cling
